name: build bootstrap installer

on:
  push:
    tags:
      - 'release-*'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            # save space on disk and in cache
            auto-optimise-store = true

      - name: get kernel source
        run: |
          free -h
          df -h
          mount
          cat /proc/cpuinfo

          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel -j0 -L || true

          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel.src -j1 -L -o kernel-src

          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel.configfile -j1 -L

          free -h
          df -h

      - name: build kernel
        run: |
          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel -j1 -L -o kernel

          free -h
          df -h

      - name: clean up kernel source
        run: |
          KERNEL_SRC=$(readlink -f kernel-src)
          rm kernel-src
          nix-store --delete $KERNEL_SRC

          free -h
          df -h


      - name: build installer
        run: |
          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap -j2 -L
          cp result/iso/*.iso $(basename result/iso/*.iso | sed s/aarch64-linux/apple-silicon-${{ github.ref_name }}/)

      - uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ./*.iso

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./*.iso
